Added new directory

diff --git a/.github/workflows/AndroidBuild.yml b/.github/workflows/AndroidBuild.yml
--- a/.github/workflows/AndroidBuild.yml
+++ b/.github/workflows/AndroidBuild.yml
@@ -28,9 +28,6 @@ jobs:
           mkdir -p app/keystore
           echo "${{ secrets.KEYSTORE_CONTENT }}" | base64 --decode > app/keystore/ibkart.jks
 
-      - name: List Keystore Directory
-        run: ls -R app/keystore
-
       - name: Clean Build
         run: ./gradlew clean
 
@@ -45,15 +42,18 @@ jobs:
       - name: Build with Gradle
         run: ./gradlew assembleRelease
 
-      - name: List AAB Output Directory
-        run: ls -R app/build/outputs/bundle/release  # Check if the AAB file was generated
+      - name: List All Output Directories
+        run: ls -R app/build/outputs  # List all output directories
 
       - name: Create Release Directory
         run: mkdir -p app/release  # Create the directory if it doesn't exist
 
       - name: Move AAB to Release Directory
         run: |
-          mv app/build/outputs/bundle/release/app-release.aab app/release/ || echo "AAB file not found."
+          # Attempt to find and move the AAB file
+          mv app/build/outputs/bundle/release/app-release.aab app/release/ || echo "First path not found."
+          mv app/build/outputs/bundle/release/outputs/bundle/release/app-release.aab app/release/ || echo "Second path not found."
+          mv app/build/outputs/bundle/release/*.aab app/release/ || echo "AAB file not found."
 
       - name: List Release Directory
         run: ls -R app/release  # List the contents of the release directory
@@ -91,3 +91,6 @@ jobs:
           status: inProgress
           inAppUpdatePriority: 2
           userFraction: 0.33
+          #whatsNewDirectory: distribution/whatsnew  # Uncomment if needed and directory exists
+          #mappingFile: app/build/outputs/mapping/release/mapping.txt  # Adjust if needed
+          #debugSymbols: app/intermediates/merged_native_libs/release/out/lib  # Adjust if needed
